{% set name = "django-cleanup" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 922e06ef8839c92bd3ab37a84db6058b8764f3fe44dbb4487bbca941d288280a

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - django >=2.2

test:
  imports:
    - django_cleanup

about:
  home: https://github.com/un1t/django-cleanup
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Deletes old files in Django Apps

extra:
  recipe-maintainers:
    - tschoonj
