{% set name = "django-cleanup" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 84f0c0e0a74545adae4c944a76ccf8fb0c195dddccf3b7195c59267abb7763dd

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python
    - django

test:
  imports:
    - django_cleanup

about:
  home: https://github.com/un1t/django-cleanup
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Deletes old files in Django Apps

extra:
  recipe-maintainers:
    - tschoonj
