{% set name = "django-cleanup" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8976aec12a22913afb3d1fcb541b1aedde2f5ec243e4260c5ff78bb6aa75a089

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python
    - django

test:
  imports:
    - django_cleanup

about:
  home: https://github.com/un1t/django-cleanup
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Deletes old files in Django Apps

extra:
  recipe-maintainers:
    - tschoonj
