travis:
  secure:
    BINSTAR_TOKEN: cpnYrGTTO05Q/3OcQiO7eB9fmqInSFskwgDgZqv123QuSw+8cPmeHOscv7XcjX8Z9zhwrY5ISrqLBKTDpzEuLIJvD+qXzSG2b0k+RkY0TOwbvaCWXbFCb9IQqAyB0kBPUSionpsnEQRAJi31dfHjU8ps4eWQQLrxZiSpVwAfSEFwbQS+tJCQUP0HxA9ECqyHZRXDMYg0LcARlMqf8e275CYON1Bcs/6PUZfBVqvBDxxjA52/zUacvDC3ikE6daWup3ds3iRULApbQsBNt9Sd188vdnKIw2AxkzMUIVNAA8lITfTqOevIRlWu3nj5LpGdXhljpO4PoHdu/SR99jUpyNsYdLmtTUUuNxM/XCIe1Ts4ekNlq5EDjqwEI4gLCl9kj2X3egVrukKqVf6gDkJzwgu7rLOztZeROq5q67k9cZOo72uzuFjv/iAVGJ6CZO4BRyxJ6U4xfgbZlLLSMu0JT7lMOa5XYwuj5oCPpB/ArN0LnOacUZJgO0+PW76t8zFePCtZanLaw43HJcEzBqnB7TBXnbioGiji1Tj1RWOFE+akWB97h+5x3qhW4zJNxh7jjssmXvDBE+eGA4d5s+ZvJeN548u26hgncxmr6Bai/DeA0E62jtvtB3joT3Ym1o0QFieKmCQNh52XEP0NyJOa3GbS9dIBP+4HgMp3SN/7/QI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
