travis:
  secure:
    BINSTAR_TOKEN: A/r+1pAXYdyL+6+wcoYCPy8NopmAt6KdBGuXhRU/e2ediGaR3BygBeEvWyIuju6/lAcKAinip8c4u/HetwyQvxsdBxEjDGqGHC5z7fTpr7on+Kyq1c3h9vAVzO+959qZAYdJTqFxvm9UFxJDnJHnnGpuMV46WHOmS8K1qnyckt1Q1soCnvier9KDiMRydeOv59Itp33ysaO6Je/7KgrKrfko3AmH3FrlAkZIY7PmruP9kohronfib992z5ga7GleaGJKwtPVMifs2+wT5og7a0vvrV6/RSbNC7spJoOOwLevPEe3vuLgbWzFSQCsz4CRt/D83+6WUEB34UCuII5MPPLWBTP7v4Wop6Gl6/H0kdqAHHBWxcQCJ6HtIQFA3BVcTV1IB0+mmsYB8AL2Cc0SZdWGFzR7LN1MPrgdbmaZXv0iO31YFoz1H780DzW71PvjgaEjAah0o8UPUk5C7Utf/yN/b/qNsePMuZJSJFTMnH4tPcBcCetDO074m45f/BeSmEviCXK2MYYmug3IPC7bGTfu0EpFTnYjkLlZ0FpIXmJXwUp/G4bHNnQwCAEWw6WryAuLaByUR6tGYAhQa0jciPty8LQO4sZZB60K8UZTkdgxWOCaZozOSW24wsaFHSzmwP0gjVsuWboQ5uQidx7G0Aeuoe7ywHjr6vdtGwDUNtw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
